version: '3.4'

services:
  metircsplayground:
    image: ${DOCKER_REGISTRY-}metircsplayground
    build:
      context: .
      dockerfile: MetircsPlayground/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
        - 8082:80
        - 8084:443 
  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro   
    
